# Generated by Django 2.0.6 on 2018-06-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('steamid', models.CharField(max_length=50)),
                ('flags', models.CharField(default='bcdfjgoe', max_length=40)),
                ('immunity', models.IntegerField(default=1)),
                ('ht_name', models.CharField(max_length=100)),
                ('ht_passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
