# Generated by Django 2.0.6 on 2018-07-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='bans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='kicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='map_changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='sm_chats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='sm_says',
            field=models.IntegerField(default=0),
        ),
    ]
