# Generated by Django 2.2 on 2019-04-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20180705_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('steamid', models.CharField(max_length=50)),
                ('flags', models.CharField(default='t', max_length=40)),
                ('immunity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='vip_admin',
            field=models.BooleanField(default=False),
        ),
    ]
