# Generated by Django 2.0.6 on 2018-07-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlogs',
            fields=[
                ('seqid', models.AutoField(primary_key=True, serialize=False)),
                ('srvid', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('steamid', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=192)),
                ('team', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'chatlogs',
                'managed': False,
            },
        ),
    ]
