# Generated by Django 2.0.6 on 2018-06-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAnalytics',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('server_ip', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('auth', models.CharField(blank=True, max_length=32, null=True)),
                ('connect_time', models.IntegerField()),
                ('connect_date', models.DateField()),
                ('connect_method', models.CharField(blank=True, max_length=64, null=True)),
                ('numplayers', models.IntegerField()),
                ('map', models.CharField(max_length=64)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('flags', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_code3', models.CharField(blank=True, max_length=3, null=True)),
                ('premium', models.IntegerField(blank=True, null=True)),
                ('html_motd_disabled', models.IntegerField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'player_analytics',
                'managed': False,
            },
        ),
    ]
